color: amber
fieldLayouts:
  8b953406-ee20-47d1-b979-be7951d30538:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-27T13:25:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 812d96dc-3109-45c2-ac53-64f975e114d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-27T13:28:37+00:00'
            elementCondition: null
            fieldUid: caef1356-0349-4d6c-a6e7-3cb9cbf4caae # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a8c79ba-82ac-4400-a733-b3004486df09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-27T14:22:13+00:00'
            elementCondition: null
            fieldUid: ac863cc6-fab1-408a-a142-70ca9f1dadf1 # Dynamic Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ca4a494-dc20-4887-8c8f-23ebc633eb25
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5078f04-89ea-47bc-aab9-4011cd0398f2
        userCondition: null
handle: adventures
hasTitleField: true
icon: campground
name: Adventures
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
