color: yellow
fieldLayouts:
  3590c1db-5ca9-4e29-a8b2-b2329a892a20:
    cardView:
      - dateCreated
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-10T10:18:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47097764-daef-4bab-a1e4-d4019eeef5c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T11:08:02+00:00'
            elementCondition: null
            fieldUid: 476880a7-807b-4837-bc80-1918ffd94639 # Bill User
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa9c9a35-8392-4fed-b4f3-e18016df1c88
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T10:17:12+00:00'
            elementCondition: null
            fieldUid: b6fae5d4-ae98-4877-aa27-aa289d0ca3d6 # Bill Items
            handle: bill_items
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc9e0121-1029-44b0-b428-cad543bf3035
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T10:55:58+00:00'
            elementCondition: null
            fieldUid: 150c102d-f991-419c-a945-f3421acce4c0 # Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9ac0182-55cc-4d9f-a842-8a70e4f80bdf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24b99625-a8e1-4ed2-a3c4-060c1c443ec9
        userCondition: null
handle: bills
hasTitleField: true
icon: table-list
name: Bills
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
