color: red
fieldLayouts:
  55bd1482-1257-427a-bf6f-041874bd173e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-27T14:17:48+00:00'
            elementCondition: null
            fieldUid: 3e3c8669-7e71-4e90-8abc-41878a67915a # <<<<Data
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3c0a3a1-23d3-4c6a-9257-3f12e0ff44f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1054ae2e-3903-4076-bfde-143a1e6fd9c6
        userCondition: null
handle: description
hasTitleField: false
icon: arrow-right
name: Description
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
