color: yellow
fieldLayouts:
  71286f38-ae2d-4ed8-ae17-c77fd6bae038:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-13T13:37:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5a25047a-674a-4fd2-826c-bb0d2d387344
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T13:40:48+00:00'
            elementCondition: null
            fieldUid: 0fa2114d-a126-45d6-9a44-398ac1506685 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b263b93-b826-4a93-8298-a729fff3af22
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a8c9f3a-b344-45c5-84ac-c085afe2d262
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
