color: yellow
fieldLayouts:
  99f24052-cd6c-4a7e-91bf-f6904f9d8958:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-10T20:06:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 21a37b85-51ae-476a-bd4f-14552bf10421
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T20:09:17+00:00'
            elementCondition: null
            fieldUid: 586e0402-4f95-4bd6-bf66-163ceddb661a # Stash User
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04c92e61-e13b-4d53-9944-f6fc9ba1fe49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T20:18:05+00:00'
            elementCondition: null
            fieldUid: ceae2617-0f34-4fa2-a6a2-46cb108b01c1 # Stash Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4659fea-dd90-4399-ab8a-ce1c8a3110d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T20:38:48+00:00'
            elementCondition: null
            fieldUid: 1c53ab5c-fc30-4d59-8097-ad14208a07f6 # Stash Status
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2f7446d-322e-40a3-b713-5380fdb819d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec19491b-df9d-49f4-8a28-c4003325983e
        userCondition: null
handle: stash
hasTitleField: true
icon: album-collection
name: Stash
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
