columnSuffix: null
handle: description
instructions: null
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: 300
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
