dateModified: 1731505253
email:
  fromEmail: frederick@rogerthat.be
  fromName: 'Craft Adventure'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0fa2114d-a126-45d6-9a44-398ac1506685: Subtitle # Subtitle
    2c4508b1-08d6-4a8d-8f93-f65a3567bd33: 'Craft Adventure' # Craft Adventure
    4ab0679b-8d81-40c7-9ae6-ed83c81f7709: 'Public Schema' # Public Schema
    4ae55be6-0fdb-40d0-b398-0428c85d6271: 'Craft Adventure' # Craft Adventure
    65ac9c48-7e34-4d8d-9817-19e9308fa99a: Homepage # Homepage
    9450365f-cc76-4e56-aca0-d4c709fbd40b: Homepage # Homepage
system:
  edition: solo
  live: true
  name: 'Craft Adventure'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
