defaultPlacement: end
enableVersioning: true
entryTypes:
  - 21a4e535-9f06-437c-b479-15efca73c46d # Stash
handle: stash_section
maxAuthors: 1
name: Voorraad
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4ae55be6-0fdb-40d0-b398-0428c85d6271: # Craft Adventure
    enabledByDefault: true
    hasUrls: true
    template: voorraad/_entry.twig
    uriFormat: 'voorraad/{slug}'
type: channel
